### ISSUE TITLE
Recently receive error, 

### ISSUE THREAD

**Issue by daktak** [felfert/matrix-ytdl#1]
synapse - 1.77.0
matrix-nio 0.20.1

Traceback (most recent call last):
  File "/pub/git/matrix-ytdl/matrix-ytdl", line 543, in <module>
    loop.run_until_complete(main(dl))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/pub/git/matrix-ytdl/matrix-ytdl", line 382, in main
    config = json.load(f)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by daktak** [comment]
config file got corrupted
